import 'bootstrap/dist/css/bootstrap.css'; // Add this line

import { Montserrat } from 'next/font/google';

import { ApolloWrapper } from '@/lib/apollo-wrapper';
import './globals.css';
import Header from './components/Header';
import Footer from './components/Footer';
import Head from 'next/head';
import HeaderWrap from './components/HeaderWrap';
import { ReactProviders } from './redux/Provider';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont',
});

export const metadata = {
  title: `Thuong shoe's store`,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        />
      </head>

      <ReactProviders>
        <body
          className={`${montserrat.variable} font-mont 
       `}
        >
          <HeaderWrap />
          {/* <ApolloWrapper>{children}</ApolloWrapper> */}
          {children}
          <Footer />
        </body>
      </ReactProviders>
    </html>
  );
}
