import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.css'; // Add this line
import MyNavbar from './components/MyNavbar';
import { Montserrat } from 'next/font/google';
import { Providers } from '@/redux/provider';
import Cart from './components/OldCart';
import './globals.css';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont',
});

export const metadata = {
  title: 'Thuong shoe store',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        />
      </head>

      <Providers>
        <body
          className={`${montserrat.variable} font-mont 
        w-full min-h-screen h-full`}
        >
          <MyNavbar />
          <Cart />
          {children}
        </body>
      </Providers>
    </html>
  );
}
